In [1]:
import pandas as pd


data = pd.read_csv(
"../data/processed/final_aml_dataset.csv"
)


data.head()

,txId,time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,class,transaction_velocity,night_transaction,high_amount_flag,anomaly,is_suspicious,risk_score,risk_level,degree,centrality
0,0,-1.556878,0.307025,1.168821,-0.748109,7.643807,-0.053406,6.039024,21.528480,-0.146334,...,2,2147,0,0,1,False,30,LOW,NaN,NaN
1,1,-1.556878,0.067780,0.271911,-0.226081,2.628539,-0.053406,2.820415,1.501088,-0.146334,...,2,2147,0,0,1,False,30,LOW,NaN,NaN
2,2,-1.556878,-0.135517,-0.222646,-1.270138,-0.183761,-0.041930,-0.187137,-0.080022,-0.102664,...,2,2147,0,0,1,False,30,LOW,NaN,NaN
3,3,-1.556878,-0.140505,-0.222646,-1.270138,-0.183761,-0.041930,-0.187137,-0.080022,-0.108753,...,2,2147,0,0,1,False,30,LOW,NaN,NaN
4,4,-1.556878,-0.170324,-0.222646,-1.270138,-0.090018,-0.041930,-0.134373,0.447015,-0.146324,...,2,2147,0,0,1,False,30,LOW,NaN,NaN

In [3]:
import sys
from pathlib import Path

project_root = next(
    path for path in [Path.cwd(), *Path.cwd().parents]
    if (path / "src").is_dir()
)

sys.path.insert(0, str(project_root))

from src.explainability import (
    generate_explanation,
    investigation_priority,
)

In [4]:
data["risk_reason"] = data.apply(
    generate_explanation,
    axis=1
)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18204\2591182404.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["risk_reason"] = data.apply(

In [5]:
data["priority"] = data["risk_score"].apply(
    investigation_priority
)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18204\2824542531.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["priority"] = data["risk_score"].apply(

In [8]:
data[
[
"risk_score",
"risk_level",
"risk_reason",
"priority"
]
].head(10)

   risk_score risk_level                  risk_reason priority
0          30        LOW  [High transaction velocity]   MEDIUM
1          30        LOW  [High transaction velocity]   MEDIUM
2          30        LOW  [High transaction velocity]   MEDIUM
3          30        LOW  [High transaction velocity]   MEDIUM
4          30        LOW  [High transaction velocity]   MEDIUM
5          30        LOW  [High transaction velocity]   MEDIUM
6          30        LOW  [High transaction velocity]   MEDIUM
7          30        LOW  [High transaction velocity]   MEDIUM
8          30        LOW  [High transaction velocity]   MEDIUM
9          30        LOW  [High transaction velocity]   MEDIUM

In [9]:
investigation_queue = data[
    data["risk_level"]=="HIGH"
]

In [10]:
investigation_queue.to_csv(
"../data/processed/investigation_queue.csv",
index=False
)

In [11]:
from src.report_generator import transaction_report


print(
transaction_report(
data.iloc[0]
)
)

Transaction ID:
0


Risk Score:
30/100


Risk Level:
LOW


Reasons:
['High transaction velocity']


Priority:
MEDIUM